### PR TITLE
fix(TBD-12497): CDP 7.1.6 support via dynamic distribution

### PR DESCRIPTION
**Pull request by mtuhai**
**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

### CODE REVIEW

**Review by AlixMetivier — APPROVED** [review]
looks good, replaced 7.1.1.0-565 with 7.1.6.3-1

**Review by firefryy — APPROVED** [review]
lgtm

**Review by cbadillo1603 — APPROVED** [review]
reviewed

**Review by lbourgeois — COMMENTED** [review]
This PR is about adding a built-in CDP 7.1.6. I thought the need from Jira ticket was to have this version in dynamic distro wizard

**Comment by mtuhai** [comment]
> This PR is about adding a built-in CDP 7.1.6. I thought the need from Jira ticket was to have this version in dynamic distro wizard

Curently I do not know how to make it appear in list. List of available versions comes from Cloudera side and it does not contain now 7.1.6

**Pull request closed without merging**
