### PR TITLE
fix(TBD-11388): Compilation error with MapRDBOutput component

### PR DESCRIPTION
**Pull request by mtuhai**
**Please check if the PR fulfills these requirements**

- [X] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [X] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [X] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [X] Docs have been added / updated (for bug fixes / features) ?
- [X] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)
TBD-11388

**What is the new behavior?**
Fixed

**BREAKING CHANGE**

TBD-11040

### CODE REVIEW

**Review by CarlosTalend — DISMISSED** [review]

**Review by lbourgeois — DISMISSED** [review]
LGTM

**Comment by lbourgeois** [comment]
build-patch

**Comment by talend-jphautin** [comment]
build-patch

**Comment by ikulish** [comment]
build-patch

**Comment by ikulish** [comment]
build-patch

**Comment by lbourgeois** [comment]
build-patch

**Review by CarlosTalend — APPROVED** [review]

**Pull request merged**
