### PR TITLE
fix(TBD-10291): R2020.9:  fix parquet prefix package for HDP3 and CDH6 

### PR DESCRIPTION
**Pull request by talend-jphautin**
**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

TBD-10291

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:
linked to PR https://github.com/Talend/tbd-studio-ee/pull/1756
backport of https://github.com/Talend/tbd-studio-se/pull/1332

### CODE REVIEW

**Comment by talend-jphautin** [comment]
build in progress : https://jenkins-studio.datapwn.com/job/tbd-studio-se/job/tbd-studio-se-build/771/

**Review by Redwene — DISMISSED** [review]
lgtm

**Comment by talend-jphautin** [comment]
patch build : https://jenkins-studio.datapwn.com/job/patches/job/patch-manual-build/1831/

**Comment by talend-jphautin** [comment]
new patch build (rebase): https://jenkins-studio.datapwn.com/job/patches/job/patch-manual-build/1888/

**Pull request merged**
