### PR TITLE
TBD-3343: make sure enable to import the hive embedded in win

### PR DESCRIPTION
**Pull request by ggu-talend**

### CODE REVIEW

**Comment by pbailly** [comment]
Could you supress the code instead of commenting it?

**Comment by ggu-talend** [comment]
if check the OS in each distributions, in the wizard or parameters, won't be displayed, so caused this bug to import the items.
so, just enable to create embedded hive in win, when do "test connection", just warning user "Don't support embedded in win" same as before.

**Comment by pbailly** [comment]
I accept it due to time constraint, but I really do not like dead code, so please, make another one where you delete unecessary.

**Comment by ggu-talend** [comment]
OK, I see

**Pull request merged**
