### PR TITLE
TBD-3418: Don't support hive in Microsoft HD Insight

### PR DESCRIPTION
**Pull request by ggu-talend**

### CODE REVIEW

**Comment by rdubois** [comment]
The Hive components support HD Insight. This commit removes HD Insight from the list of supported distributions in the components. We can't accept it.

**Comment by nrousseau** [comment]
Till now all the hd insight retrieve the tables from hbase wizard only in fact.
We have an issue still opened on this, and not fixed (since the standard way to retrieve hive table totally doesn't work for hd insight..)

**Comment by nrousseau** [comment]
But of course this only concerns the wizard... components should still works same as before

**Comment by rdubois** [comment]
Yes. I suggest to add a isHiveSupportedByWizard method in the HiveComponent interface and to use this method to hive the distribution on the wizard side but not on the components side.

**Comment by ggu-talend** [comment]
Try another way to fix the issue. so close this one

**Pull request closed without merging**
