### PR TITLE
fix(TDI-49284): bump talend file enhanced

### PR DESCRIPTION
**Pull request by ozhelezniak-talend**
**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

### CODE REVIEW

**Review by lbourgeois — COMMENTED** [review]
The commit on maintenance/8.0 will be automatically cherry picked when PR on maintenance/8.0 will be merged

**Comment by ozhelezniak-talend** [comment]
> The commit on maintenance/8.0 will be automatically cherry picked when PR on maintenance/8.0 will be merged

Hello @lbourgeois 
The commit on m/8.0 will, be automatically cherry-picked when PR on **master** will be merged, am I right?

**Comment by lbourgeois** [comment]
Sorry if it was not clear ; we have a jenkins job which cherry-pick every new commit from m/8.0 to apply it to master automatically so only PR + merge on m/8.0 is needed.

**Comment by ozhelezniak-talend** [comment]
we don't need this PR
the change was auto-cherry-picked:

**Pull request closed without merging**
