### PR TITLE
fix(TBD-15326): ClassNotFoundException when spark batch job use ES co…

### PR DESCRIPTION
**Pull request by sponomarova**
…mponents with spark local 2.4

**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

### CODE REVIEW

**Review by sanulich — COMMENTED** [review]
please take a look to the https://jira.talendforge.org/browse/TBD-15229 ticket were this library was deleted

**Comment by sponomarova** [comment]
> We removed usage of commons-httpclient-3.1 in https://jira.talendforge.org/browse/TBD-15229 to fix some CVE and we did not find any issue. I guess that's because RDD mode was not tested. To be checked if newer ES lib still need commons-httpclient-3.1. If yes maybe it's time to remove RDD support for ES. Also there are some dedicated module groups in sparkprovider plugin for ES libs to avoid adding them to the global Spark compile group

it's rdd part. Jira was created because tuj was failed. 
If we decide to leave rdd support for ES so far, I can create ES module group and put jar (we don't have any specific module group for ES now). Or close this jira and create one to remove rdd for ES. Don't know which is better.

**Comment by lbourgeois** [comment]
> > We removed usage of commons-httpclient-3.1 in [jira.talendforge.org/browse/TBD-15229](https://jira.talendforge.org/browse/TBD-15229) to fix some CVE and we did not find any issue. I guess that's because RDD mode was not tested. To be checked if newer ES lib still need commons-httpclient-3.1. If yes maybe it's time to remove RDD support for ES. Also there are some dedicated module groups in sparkprovider plugin for ES libs to avoid adding them to the global Spark compile group
> 
> it's rdd part. Jira was created because tuj was failed. If we decide to leave rdd support for ES so far, I can create ES module group and put jar (we don't have any specific module group for ES now). Or close this jira and create one to remove rdd for ES. Don't know which is better.

If there is no functional diff between RDD and Dataset I would keep only Dataset implem.
If we keep RDD support we have to move away from using commons-httpclient-3.1.jar (very old, 2007, has CVEs)

**Comment by sponomarova** [comment]
Closing this PR since it's not relevant now.

**Pull request closed without merging**
