### PR TITLE
fix(TBD-12112): CVE (commons-beanutils-core-1.8.0.jar)

### PR DESCRIPTION
**Pull request by mtuhai**
**Please check if the PR fulfills these requirements**

- [X] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [X] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [X] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [X] Docs have been added / updated (for bug fixes / features) ?
- [X] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)
TBD-12112

**What is the new behavior?**
fixed

### CODE REVIEW

**Review by ikulish — APPROVED** [review]

**Review by lbourgeois — COMMENTED** [review]
Could you also clean ref to this jar in localprovider please (plugin + tHive components) ?
Also could you check if last versions of each dynamic distro upgraded this dependency or not

**Comment by mtuhai** [comment]
> Could you also clean ref to this jar in localprovider please (plugin + tHive components) ?
> Also could you check if last versions of each dynamic distro upgraded this dependency or not

Done
https://github.com/Talend/tdi-studio-se/pull/6012

**Review by cbadillo1603 — DISMISSED** [review]
reviwed

**Comment by mtuhai** [comment]
> I can't see any changes on templates so I guess you updated manually generated json which is not the best solution.
> 
>     * can we update templates ?
> 
>     * are last versions of cdh6 and cdh5 still on 1.8.0 ?

I tried to find a commons-beanutils-core dependency among first-level dependencies of cdh5x and cdh6x template, but I failed. Should I look at second-level dependencies? That will be too much work IMHO

**Review by lbourgeois — DISMISSED** [review]
LGTM. Agree to not force an updated fixed version for transitive dep in template.

**Review by firefryy — DISMISSED** [review]
lgtm

**Review by lbourgeois — APPROVED** [review]
LGTM

**Review by lbourgeois — APPROVED** [review]

**Review by firefryy — APPROVED** [review]
lgtm

**Pull request merged**
